/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

/* Table schema:
CREATE TABLE kv_store_19717bce (
  key TEXT NOT NULL PRIMARY KEY,
  value JSONB NOT NULL
);
*/

// View at https://supabase.com/dashboard/project/oubdmmaqxnutbbxiqeow/database/tables

// This file provides a simple key-value interface for storing Figma Make data. It should be adequate for most small-scale use cases.
import { createClient } from "jsr:@supabase/supabase-js@2.49.8";

const client = () => createClient(
  Deno.env.get("SUPABASE_URL"),
  Deno.env.get("SUPABASE_SERVICE_ROLE_KEY"),
);

// Set stores a key-value pair in the database.
export const set = async (key: string, value: any): Promise<void> => {
  const supabase = client()
  const { error } = await supabase.from("kv_store_19717bce").upsert({
    key,
    value
  });
  if (error) {
    throw new Error(error.message);
  }
};

// Get retrieves a key-value pair from the database.
export const get = async (key: string): Promise<any> => {
  const supabase = client()
  const { data, error } = await supabase.from("kv_store_19717bce").select("value").eq("key", key).maybeSingle();
  if (error) {
    throw new Error(error.message);
  }
  return data?.value;
};

// Delete deletes a key-value pair from the database.
export const del = async (key: string): Promise<void> => {
  const supabase = client()
  const { error } = await supabase.from("kv_store_19717bce").delete().eq("key", key);
  if (error) {
    throw new Error(error.message);
  }
};

// Sets multiple key-value pairs in the database.
export const mset = async (keys: string[], values: any[]): Promise<void> => {
  const supabase = client()
  const { error } = await supabase.from("kv_store_19717bce").upsert(keys.map((k, i) => ({ key: k, value: values[i] })));
  if (error) {
    throw new Error(error.message);
  }
};

// Gets multiple key-value pairs from the database.
export const mget = async (keys: string[]): Promise<any[]> => {
  const supabase = client()
  const { data, error } = await supabase.from("kv_store_19717bce").select("value").in("key", keys);
  if (error) {
    throw new Error(error.message);
  }
  return data?.map((d) => d.value) ?? [];
};

// Deletes multiple key-value pairs from the database.
export const mdel = async (keys: string[]): Promise<void> => {
  const supabase = client()
  const { error } = await supabase.from("kv_store_19717bce").delete().in("key", keys);
  if (error) {
    throw new Error(error.message);
  }
};

// Search for key-value pairs by prefix.
export const getByPrefix = async (prefix: string): Promise<any[]> => {
  const supabase = client()
  const { data, error } = await supabase.from("kv_store_19717bce").select("key, value").like("key", prefix + "%");
  if (error) {
    throw new Error(error.message);
  }
  return data?.map((d) => d.value) ?? [];
};

// Counts keys matching a prefix without fetching any values (cheap, avoids loading large rows into memory).
export const countByPrefix = async (prefix: string): Promise<number> => {
  const supabase = client();
  const { count, error } = await supabase
    .from("kv_store_19717bce")
    .select("key", { count: "exact", head: true })
    .like("key", prefix + "%");
  if (error) {
    throw new Error(error.message);
  }
  return count ?? 0;
};

// Fetches a page of FULL values matching a prefix (inclui mídia pesada!).
// Use apenas quando o valor completo é necessário (ex.: backup/export).
// Para listagens, use getItemsLightPaged.
export const getByPrefixPaged = async (
  prefix: string,
  options: { offset?: number; limit?: number; orderByJsonField?: string; ascending?: boolean; categoryFilter?: string } = {},
): Promise<{ items: any[]; total: number }> => {
  const { offset = 0, limit = 100, orderByJsonField = "createdAt", ascending = false, categoryFilter } = options;
  const supabase = client();

  let query = supabase
    .from("kv_store_19717bce")
    .select("value", { count: "exact" })
    .like("key", prefix + "%");

  if (categoryFilter) {
    query = query.eq("value->>category", categoryFilter);
  }

  // Index idx_kv_items_createdat (DESC NULLS LAST) cobre esta ordenação.
  // É ESSENCIAL passar nullsFirst: false: sem isso o PostgREST gera
  // "ORDER BY ... DESC" que no PostgreSQL é NULLS FIRST — itens sem createdAt
  // iriam para o topo (empurrando posts novos para fora do limite/página) e o
  // índice NULLS LAST não seria usado, causando full scan + timeout na tabela
  // grande. Com NULLS LAST os mais recentes ficam no topo e o índice é usado.
  if (orderByJsonField === "createdAt") {
    query = query.order(`value->>'createdAt'` as any, { ascending, nullsFirst: false });
  }
  const { data, error, count } = await query.range(offset, offset + limit - 1);

  if (error) {
    throw new Error(error.message);
  }
  return { items: data?.map((d) => d.value) ?? [], total: count ?? 0 };
};

// Fetches a page of "light" items (função get_items_light no Postgres).
// A montagem dos itens acontece DENTRO do banco: mídia pesada em base64
// (photo/muralContent, MBs por linha) nunca sai do Postgres — antes essas
// linhas inteiras trafegavam até a edge function só para serem descartadas,
// o que deixava GET /items com 10s+ e causava 500 por timeout.
// A função replica o filtro (id/categoria/título não vazios), a ordenação
// (createdAt DESC NULLS LAST) e o mapeamento (photo -> 'HAS_PHOTO',
// muralContent só quando muralContentType === 'text').
export const getItemsLightPaged = async (
  options: { offset?: number; limit?: number; categoryFilter?: string } = {},
): Promise<{ items: any[]; total: number }> => {
  const { offset = 0, limit = 100, categoryFilter } = options;
  const supabase = client();

  const { data, error } = await supabase.rpc("get_items_light", {
    p_category: categoryFilter ?? null,
    p_offset: offset,
    p_limit: limit,
  });

  if (error) {
    throw new Error(error.message);
  }
  return { items: data?.items ?? [], total: data?.total ?? 0 };
};